# -*- coding: utf-8 -*-
"""sanaitics week 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yfn3MlJVNUvEI4iBV3gROgTafDa4bcfY
"""

#importing libraries
import pandas as pd
import numpy as np

#importing data
data = pd.read_csv('/content/Sampling Competition_8900.csv')

#mean and standard deviation of variable X
print('mean of variable X =',data.X.mean(),'\n''standard deviation of variable is X =',data.X.std())

#Generating 500 random samples of size 30 and obtaining mean and std for each one of them
Mean , Std= [],[]                                    
for i in range(500):
  df = data.X.sample(n=30,replace=True)
  Mean.append(np.mean(df));Std.append(np.std(df,ddof = 1))     

print(' Mean of 500 means is =',np.mean(Mean),'\n','Mean of 500 standard deviations is =',np.mean(Std))

"""comment:
1. Sample mean is unbiased estimator of population mean
2. Sample variance is unbiased estimator of population variance 
3. But, sample standard deviation is not an unbiased estimate of population standard deviation. It contains some biased factor
4. In our case sample size n is large, therefore n is approximately equal to n-1 hence sample standard deviation becomes unbiased estimate of population standard deviation.
"""